### ISSUE TITLE
problem when installing on linux (colorname)

### ISSUE THREAD

**Issue by jeromew** [skratchdot/color-stats#1]
the colorname dependency has a line

```
var Color = require('Color');
```

to require the "color" module. This works on OS that mix uppercases and lowercases (like windows) but not on all linux versions.

Upon running I get 

```
Error: Cannot find module 'Color'
at Function.Module._resolveFilename (module.js:336:15)
```

I could not find the github associated with 'colorname' so I thought I would post the issue here in case you know where the code is hosted.

**Comment by skratchdot** [comment]
Weird. Thanks for reporting this.  Here's the module: https://www.npmjs.com/package/colorname 
Seems weird because their README says to `npm install color-name` which is a different module!

After some hunting, I found: https://github.com/perfectworks/colorname

We should submit a PR to that repo, fixing the README, the case-sensitivity issue you found, update the package.json version number, and ask @perfectworks to publish the fixes to NPM.  Thanks again for the report.

**Comment by skratchdot** [comment]
Looks like there's already a PR for the 'Color' fix: https://github.com/perfectworks/colorname/pull/1

**Comment by skratchdot** [comment]
Ok. I submitted a PR w/ some a few changes: https://github.com/perfectworks/colorname/issues/3

**Comment by e7h4n** [comment]
I'm in vacation, and will fix this after Oct 12. Sorry for that.

◬ notifications@github.com于2015年10月6日周二 下午2:04写道：

**Comment by skratchdot** [comment]
Thanks for your help.  Have a good vacation!

**Comment by jeromew** [comment]
Thanks for your help. (and for your work on both of your great modules !)
